import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

export const lists = query({
  args: { chatId: v.id("chats") },
  handler: async (ctx, args) => {
    const messages = await ctx.db
      .query("messages")
      .withIndex("by_chats", (q) => q.eq("chatId", args.chatId))
      .order("asc")
      .collect();

    return messages;
  },
});

export const send = mutation({
  args: {
    chatId: v.id("chats"),
    content: v.string(),
  },
  handler: async (ctx, args) => {
    const messageId = await ctx.db.insert("messages", {
      chatId: args.chatId,
      content: args.content.replace(/\n/g, "\\n"),
      role: "user",
      createdAt: Date.now(),
    });
    return messageId;
  },
});

export const store = mutation({
  args: {
    chatId: v.id("chats"),
    content: v.string(),
    role: v.union(v.literal("user"), v.literal("assistant")),
  },
  handler: async (ctx, args) => {
    //Store message with preserved newlines and HTML
    const messageId = await ctx.db.insert("messages", {
      chatId: args.chatId,
      content: args.content
        .replace(/\n/g, "//n")
        // Don't escape HTML -we trust the content as since it's generated by our system
        .replace(/\\/g, "////"), // Only escape backslashes
      role: args.role,
      createdAt: Date.now(),
    });
    return messageId;
  },
});

export const getLastMessage = mutation({
  args: { chatId: v.id("chats") },
  handler: async (ctx, args) => {
    const isAuthenticated = await ctx.auth.getUserIdentity();
    if (!isAuthenticated) {
      throw new Error("user not authenticated");
    }

    const chat = await ctx.db.get(args.chatId);
    if (!chat || chat.userId !== isAuthenticated.subject) {
      throw new Error("Unauthorised");
    }

    const messages = await ctx.db
      .query("messages")
      .withIndex("by_chats", (q) => q.eq("chatId", args.chatId))
      .order("desc")
      .first();

    return messages;
  },
});
